import xarray as xr
from py_wake.wind_farm_models.wind_farm_model import SimulationResult

# 读取为 xarray.Dataset
result = xr.open_dataset("simulation_result.nc")

# 可选：如果你需要强制转换回 SimulationResult，可以这样（非必要）
#print(result)
print("Dimensions:", result.dims)
print("Variables:", result.data_vars)

'''
Dimensions: FrozenMappingWarningOnValuesAccess({'wt': 80, 'wd': 360, 'ws': 23})
Variables: Data variables:
    WS_eff            (wt, wd, ws) float64 5MB ...
    TI_eff            (wt, wd, ws) float64 5MB ...
    Power             (wt, wd, ws) float64 5MB ...
    CT                (wt, wd, ws) float64 5MB ...
    h                 (wt) float64 640B ...
    x                 (wt) int64 640B ...
    y                 (wt) int64 640B ...
    WD                (wd) int64 3kB ...
    TI                float64 8B ...
    wd_bin_size       int64 8B ...
    WS                (ws) int64 184B ...
    ws_l              (ws) float64 184B ...
    ws_u              (ws) float64 184B ...
    Weibull_A         (wd) float64 3kB ...
    Weibull_k         (wd) float64 3kB ...
    Sector_frequency  (wd) float64 3kB ...
    P                 (wd, ws) float64 66kB ...
    aep_with_wake     (wt, wd, ws) float64 5MB ...
    aep_without_wake  (wt, wd, ws) float64 5MB ...
'''
